version: "3.9"
services:
  nirvarango:
    env_file: ./.env
    build:
      context: .
      dockerfile: Dockerfile
    # u cannot scale a service beyond 1 container
    # if supplying a static container name
    container_name: nirvarangofoss
    ports:
      - "8529:8529"
